security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
         prospecter_provider:
             id: App\Security\ProspecterUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            host: '%app_application_host%'
            pattern: ^(?!/build|/storage)
            anonymous: ~
            logout:
                path: /logout
                target: /login
            guard:
                authenticators:
                    - App\Security\ProspecterAuthenticator
        static:
            host: '%app_static_host%'
            security: false

    access_control:
        - { host: '%app_application_host%', path: ^/(?!login), roles: ROLE_PROSPECTOR}
