twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        google_api_key: '%env(APP_GOOGLE_API_KEY)%'
    form_themes:
        - 'form/bootstrap_4_layout.html.twig'
