version: '2.3'
services:
  php-fpm:
    build:
      context: docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    init: true
    volumes:
      - ./:/var/www/src
    networks:
      - back
      - front
    container_name: pro-php
  nginx:
    build: docker/nginx
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    depends_on:
      - php-fpm
    volumes_from:
      - php-fpm
    networks:
      - front
    environment:
      - NGINX_HOST=local.prospecter.io
      - NGINX_STATIC_HOST=static.local.prospecter.io
    container_name: pro-nginx
    volumes:
      - ./docker/data/ssl/certs/:/etc/ssl/certs
networks:
  front:
    driver: bridge
  back:
    driver: bridge
