# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    google_api_url : 'https://maps.googleapis.com/maps/api/geocode/json'
    knp_menu.renderer.twig.options:
        currentClass: 'active'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #controller
    App\Controller\ProspectController:
        tags: ['controller.service_arguments']
        calls:
            - [setFormFactory, ['@form.factory']]
            - [setTwig, ['@twig']]
            - [setRouter, ['@router']]
            - [setUseCases, ['@Solean\CleanProspecter\UseCase\UseCasesFacade']]
            - [setFormHandler, ['@App\Service\RequestHandler']]
    App\Controller\OrganizationController:
        tags: ['controller.service_arguments']
        calls:
            - [setFormFactory, ['@form.factory']]
            - [setTwig, ['@twig']]
            - [setRouter, ['@router']]
            - [setUseCases, ['@Solean\CleanProspecter\UseCase\UseCasesFacade']]
            - [setFormHandler, ['@App\Service\RequestHandler']]

    #Security
    App\Security\ProspecterAuthenticator:
        arguments:
            - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
            - '@Symfony\Component\Form\FormFactoryInterface'
            - '@Symfony\Component\HttpFoundation\Session\SessionInterface'
            - '@Solean\CleanProspecter\UseCase\UseCasesFacade'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - 'login'
            - 'dashboard_display'
            - 'prospecter_provider'
    App\Security\ProspecterUserProvider:
        arguments: ['@Solean\CleanProspecter\UseCase\UseCasesFacade']
    #Menu
    App\Menu\Matcher\PathInfoRegexVoter:
        arguments: ['@request_stack']
        tags: ['knp_menu.voter']
    App\Menu\MenuBuilder:
        arguments: ["@knp_menu.factory", "@security.authorization_checker", "@=service('request_stack').getCurrentRequest()"]
        tags:
            - { name: 'knp_menu.menu_builder', method: 'createMainMenu', alias: 'main' }
            - { name: 'knp_menu.menu_builder', method: 'createLeftMenu', alias: 'left' }
            - { name: 'knp_menu.menu_builder', method: 'createRightMenu', alias: 'right' }
            - { name: 'knp_menu.menu_builder', method: 'createBreadcrumb', alias: 'breadcrumb' }

    #Uses Cases
    Solean\CleanProspecter\UseCase\UseCasesFacade: ~
    Solean\CleanProspecter\UseCase\Login\LoginImpl:
        lazy:  true
        tags: ['use_case']
        arguments:
            - '@App\Gateway\Entity\UserRepositoryAdapter'
    Solean\CleanProspecter\UseCase\RefreshUser\RefreshUserImpl:
        lazy:  true
        tags: ['use_case']
        arguments:
            - '@App\Gateway\Entity\UserRepositoryAdapter'
    Solean\CleanProspecter\UseCase\CreateOrganization\CreateOrganizationImpl:
        lazy:  true
        tags: ['use_case']
        arguments:
            - '@App\Gateway\Entity\OrganizationRepositoryAdapter'
            - '@App\Gateway\StorageLocalAdapter'
            - '@App\Gateway\UserNotifierSymfonyAdapter'
            - '@App\Gateway\GeoLocatorAdapter'
    Solean\CleanProspecter\UseCase\UpdateOrganization\UpdateOrganizationImpl:
        lazy:  true
        tags: ['use_case']
        arguments:
            - '@App\Gateway\Entity\OrganizationRepositoryAdapter'
            - '@App\Gateway\StorageLocalAdapter'
            - '@App\Gateway\UserNotifierSymfonyAdapter'
            - '@App\Gateway\GeoLocatorAdapter'
    Solean\CleanProspecter\UseCase\GetOrganization\GetOrganizationImpl:
        lazy:  true
        tags: ['use_case']
        arguments:
            - '@App\Gateway\Entity\OrganizationRepositoryAdapter'
    Solean\CleanProspecter\UseCase\FindOrganization\FindOrganizationImpl:
        lazy:  true
        tags: ['use_case']
        arguments:
            - '@App\Gateway\Entity\OrganizationRepositoryAdapter'
    #Gateway
      #Database
    App\Gateway\Entity\UserRepositoryAdapter:
        lazy:  true
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Solean\CleanProspecter\Entity\User'
    App\Gateway\Entity\OrganizationRepositoryAdapter:
        lazy:  true
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Solean\CleanProspecter\Entity\Organization'
      #User Notifier
    App\Gateway\UserNotifierSymfonyAdapter:
        arguments:
            - '@session'
      #Storage
    App\Gateway\StorageLocalAdapter:
        arguments:
            - '@App\Service\LocalStorageService'
      #GeoLocation
    App\Gateway\GeoLocationAdapter:
        arguments:
            - '@App\Service\GoogleMapGeoLocator'
    #Service
      #Local storage
    App\Service\LocalStorageService:
        arguments:
            - '%env(resolve:STORAGE_PATH)%'
            - '%env(STORAGE_URL)%'
      #Google Map geo locator
    App\Service\GoogleMapGeoLocator:
        arguments:
            - '%google_api_url%'
            - '%env(GOOGLE_API_KEY)%'
      #Request handler
    App\Service\RequestHandler: ~
      #Form Request handler command
    App\Service\RequestHandler\AbstractFormHandlingCommand:
        abstract: true
        calls:
            - [setFormFactory, ['@form.factory']]
            - [setTwig, ['@twig']]
            - [setRouter, ['@router']]
            - [setUseCases, ['@Solean\CleanProspecter\UseCase\UseCasesFacade']]

    App\Service\RequestHandler\CreateFormHandlingCommand:
        autoconfigure: false
        autowire: false
        public: false
        parent: App\Service\RequestHandler\AbstractFormHandlingCommand
        lazy:  true
        tags: [{name: 'form_cmd', id: 'create'}]
    App\Service\RequestHandler\UpdateFormHandlingCommand:
        autoconfigure: false
        autowire: false
        public: false
        parent: App\Service\RequestHandler\AbstractFormHandlingCommand
        lazy:  true
        tags: [{name: 'form_cmd', id: 'update'}]

