Solean\CleanProspecter\Entity\User:
  type: entity
  manyToOne:
    organization:
      targetEntity: Organization
      inversedBy: applicationUsers
  fields:
    roles:
      type: array
    password:
      type: string
      length: 32
      nullable: false
    userName:
      type: string
      length: 50
    salt:
      type: string
      length: 32
    firstName:
      type: string
      length: 100
    lastName:
      type: string
      length: 100
    hasPicture:
      type: boolean
  embedded:
    picture:
      class: File
